// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrafoTestSistemi.Models;

#nullable disable

namespace TrafoTestSistemi.Migrations
{
    [DbContext(typeof(TrafoContext))]
    [Migration("20260322192052_ExtendedTrafoDetails")]
    partial class ExtendedTrafoDetails
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrafoTestSistemi.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NameSurname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TrafoTestSistemi.Models.TrafoTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BaglantiGrubu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("CekirdekAgirlik")
                        .HasColumnType("float");

                    b.Property<string>("CekirdekTipi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DizaynId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DizaynTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("ElektrikMuhendisi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Frekans")
                        .HasColumnType("int");

                    b.Property<double>("GerilimAG")
                        .HasColumnType("float");

                    b.Property<double>("GerilimYG")
                        .HasColumnType("float");

                    b.Property<double>("Guc")
                        .HasColumnType("float");

                    b.Property<string>("KazanCinsi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MekanikMuhendisi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Musteri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("P0_Garanti")
                        .HasColumnType("float");

                    b.Property<double>("P0_Hesap")
                        .HasColumnType("float");

                    b.Property<double>("P0_Test")
                        .HasColumnType("float");

                    b.Property<double>("Pk_Garanti")
                        .HasColumnType("float");

                    b.Property<double>("Pk_Hesap")
                        .HasColumnType("float");

                    b.Property<double>("Pk_Test")
                        .HasColumnType("float");

                    b.Property<string>("ProjeAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SacCinsi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SargiIsinmaAG")
                        .HasColumnType("float");

                    b.Property<double>("SargiIsinmaYG")
                        .HasColumnType("float");

                    b.Property<string>("TasarimNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TestTarihi")
                        .HasColumnType("datetime2");

                    b.Property<double>("ToplamAgirlik")
                        .HasColumnType("float");

                    b.Property<double>("Uk_Garanti")
                        .HasColumnType("float");

                    b.Property<double>("Uk_Hesap")
                        .HasColumnType("float");

                    b.Property<double>("Uk_Test")
                        .HasColumnType("float");

                    b.Property<string>("YagCinsi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("YagIsinma")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("TestKayitlari");
                });
#pragma warning restore 612, 618
        }
    }
}
