// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrafoTestSistemi.Models;

#nullable disable

namespace TrafoTestSistemi.Migrations
{
    [DbContext(typeof(TrafoContext))]
    [Migration("20260408104455_UpdateSargiGeometrisiFields")]
    partial class UpdateSargiGeometrisiFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrafoTestSistemi.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NameSurname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TrafoTestSistemi.Models.TrafoTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AGIletken_Hesap")
                        .HasColumnType("float");

                    b.Property<double>("AGIletken_Sapma")
                        .HasColumnType("float");

                    b.Property<double>("AGIletken_Test")
                        .HasColumnType("float");

                    b.Property<double>("AG_DisCap_K_Hesap")
                        .HasColumnType("float");

                    b.Property<double>("AG_DisCap_K_Test")
                        .HasColumnType("float");

                    b.Property<double>("AG_DisCap_U_Hesap")
                        .HasColumnType("float");

                    b.Property<double>("AG_DisCap_U_Test")
                        .HasColumnType("float");

                    b.Property<double>("AG_Grad_Garanti")
                        .HasColumnType("float");

                    b.Property<double>("AG_Grad_Hesap")
                        .HasColumnType("float");

                    b.Property<double>("AG_Grad_Sapma_GH")
                        .HasColumnType("float");

                    b.Property<double>("AG_Grad_Sapma_GT")
                        .HasColumnType("float");

                    b.Property<double>("AG_Grad_Sapma_HT")
                        .HasColumnType("float");

                    b.Property<double>("AG_Grad_Test")
                        .HasColumnType("float");

                    b.Property<double>("AG_IcCap_K_Hesap")
                        .HasColumnType("float");

                    b.Property<double>("AG_IcCap_K_Test")
                        .HasColumnType("float");

                    b.Property<double>("AG_IcCap_U_Hesap")
                        .HasColumnType("float");

                    b.Property<double>("AG_IcCap_U_Test")
                        .HasColumnType("float");

                    b.Property<double>("AG_Sapma_DisCap_K")
                        .HasColumnType("float");

                    b.Property<double>("AG_Sapma_DisCap_U")
                        .HasColumnType("float");

                    b.Property<double>("AG_Sapma_IcCap_K")
                        .HasColumnType("float");

                    b.Property<double>("AG_Sapma_IcCap_U")
                        .HasColumnType("float");

                    b.Property<double>("AG_Sapma_Radyal_K")
                        .HasColumnType("float");

                    b.Property<double>("AG_Sapma_Radyal_U")
                        .HasColumnType("float");

                    b.Property<double>("AG_SargiIsinma_Garanti")
                        .HasColumnType("float");

                    b.Property<double>("AG_SargiIsinma_Hesap")
                        .HasColumnType("float");

                    b.Property<double>("AG_SargiIsinma_Sapma_GH")
                        .HasColumnType("float");

                    b.Property<double>("AG_SargiIsinma_Sapma_GT")
                        .HasColumnType("float");

                    b.Property<double>("AG_SargiIsinma_Sapma_HT")
                        .HasColumnType("float");

                    b.Property<double>("AG_SargiIsinma_Test")
                        .HasColumnType("float");

                    b.Property<string>("BaglantiGrubu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CekirdekTipi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Cekirdek_Hesap")
                        .HasColumnType("float");

                    b.Property<double>("Cekirdek_Sapma")
                        .HasColumnType("float");

                    b.Property<double>("Cekirdek_Test")
                        .HasColumnType("float");

                    b.Property<string>("DizaynId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DizaynTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("ElektrikMuhendisi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Frekans")
                        .HasColumnType("int");

                    b.Property<double>("GerilimAG")
                        .HasColumnType("float");

                    b.Property<double>("GerilimYG")
                        .HasColumnType("float");

                    b.Property<double>("Guc")
                        .HasColumnType("float");

                    b.Property<string>("KazanCinsi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MekanikMuhendisi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Musteri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("P0_Garanti")
                        .HasColumnType("float");

                    b.Property<double>("P0_Hesap")
                        .HasColumnType("float");

                    b.Property<double>("P0_Sapma_GH")
                        .HasColumnType("float");

                    b.Property<double>("P0_Sapma_GT")
                        .HasColumnType("float");

                    b.Property<double>("P0_Sapma_HT")
                        .HasColumnType("float");

                    b.Property<double>("P0_Test")
                        .HasColumnType("float");

                    b.Property<double>("P0_Tolerans")
                        .HasColumnType("float");

                    b.Property<double>("P55_ElekGaran")
                        .HasColumnType("float");

                    b.Property<double>("P55_MekHesap")
                        .HasColumnType("float");

                    b.Property<double>("P55_Sapma_EGH")
                        .HasColumnType("float");

                    b.Property<double>("P55_Sapma_MGT")
                        .HasColumnType("float");

                    b.Property<double>("P55_Sapma_MHT")
                        .HasColumnType("float");

                    b.Property<double>("P55_Test")
                        .HasColumnType("float");

                    b.Property<double>("Pk_Garanti")
                        .HasColumnType("float");

                    b.Property<double>("Pk_Hesap")
                        .HasColumnType("float");

                    b.Property<double>("Pk_Sapma_GH")
                        .HasColumnType("float");

                    b.Property<double>("Pk_Sapma_GT")
                        .HasColumnType("float");

                    b.Property<double>("Pk_Sapma_HT")
                        .HasColumnType("float");

                    b.Property<double>("Pk_Test")
                        .HasColumnType("float");

                    b.Property<double>("Pk_Tolerans")
                        .HasColumnType("float");

                    b.Property<string>("ProjeAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SacCinsi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sonuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TasarimNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TestTarihi")
                        .HasColumnType("datetime2");

                    b.Property<double>("Uk_Garanti")
                        .HasColumnType("float");

                    b.Property<double>("Uk_Hesap")
                        .HasColumnType("float");

                    b.Property<double>("Uk_Sapma_GH")
                        .HasColumnType("float");

                    b.Property<double>("Uk_Sapma_GT")
                        .HasColumnType("float");

                    b.Property<double>("Uk_Sapma_HT")
                        .HasColumnType("float");

                    b.Property<double>("Uk_Test")
                        .HasColumnType("float");

                    b.Property<double>("Uk_Tolerans")
                        .HasColumnType("float");

                    b.Property<double>("YGIletken_Hesap")
                        .HasColumnType("float");

                    b.Property<double>("YGIletken_Sapma")
                        .HasColumnType("float");

                    b.Property<double>("YGIletken_Test")
                        .HasColumnType("float");

                    b.Property<double>("YG_DisCap_K_Hesap")
                        .HasColumnType("float");

                    b.Property<double>("YG_DisCap_K_Test")
                        .HasColumnType("float");

                    b.Property<double>("YG_DisCap_U_Hesap")
                        .HasColumnType("float");

                    b.Property<double>("YG_DisCap_U_Test")
                        .HasColumnType("float");

                    b.Property<double>("YG_Grad_Garanti")
                        .HasColumnType("float");

                    b.Property<double>("YG_Grad_Hesap")
                        .HasColumnType("float");

                    b.Property<double>("YG_Grad_Sapma_GH")
                        .HasColumnType("float");

                    b.Property<double>("YG_Grad_Sapma_GT")
                        .HasColumnType("float");

                    b.Property<double>("YG_Grad_Sapma_HT")
                        .HasColumnType("float");

                    b.Property<double>("YG_Grad_Test")
                        .HasColumnType("float");

                    b.Property<double>("YG_IcCap_K_Hesap")
                        .HasColumnType("float");

                    b.Property<double>("YG_IcCap_K_Test")
                        .HasColumnType("float");

                    b.Property<double>("YG_IcCap_U_Hesap")
                        .HasColumnType("float");

                    b.Property<double>("YG_IcCap_U_Test")
                        .HasColumnType("float");

                    b.Property<double>("YG_Sapma_DisCap_K")
                        .HasColumnType("float");

                    b.Property<double>("YG_Sapma_DisCap_U")
                        .HasColumnType("float");

                    b.Property<double>("YG_Sapma_IcCap_K")
                        .HasColumnType("float");

                    b.Property<double>("YG_Sapma_IcCap_U")
                        .HasColumnType("float");

                    b.Property<double>("YG_Sapma_Radyal_K")
                        .HasColumnType("float");

                    b.Property<double>("YG_Sapma_Radyal_U")
                        .HasColumnType("float");

                    b.Property<double>("YG_SargiIsinma_Garanti")
                        .HasColumnType("float");

                    b.Property<double>("YG_SargiIsinma_Hesap")
                        .HasColumnType("float");

                    b.Property<double>("YG_SargiIsinma_Sapma_GH")
                        .HasColumnType("float");

                    b.Property<double>("YG_SargiIsinma_Sapma_GT")
                        .HasColumnType("float");

                    b.Property<double>("YG_SargiIsinma_Sapma_HT")
                        .HasColumnType("float");

                    b.Property<double>("YG_SargiIsinma_Test")
                        .HasColumnType("float");

                    b.Property<string>("YagCinsi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Yag_Hesap")
                        .HasColumnType("float");

                    b.Property<double>("Yag_Sapma")
                        .HasColumnType("float");

                    b.Property<double>("Yag_Test")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("TestKayitlari");
                });
#pragma warning restore 612, 618
        }
    }
}
